"""Create L2 metrics tables

Revision ID: c38b35702c0a
Revises: f9a8d741038f
Create Date: 2025-07-10 18:45:36.578451

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "c38b35702c0a"
down_revision: Union[str, Sequence[str], None] = "f9a8d741038f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
