"""Create L2 metrics tables properly

Revision ID: de7fdaa0c9aa
Revises: c38b35702c0a
Create Date: 2025-07-10 19:43:08.173781

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de7fdaa0c9aa"
down_revision: Union[str, Sequence[str], None] = "c38b35702c0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "l2_network_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("network", sa.String(length=50), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("gas_price_wei", sa.BigInteger(), nullable=True),
        sa.Column("gas_price_gwei", sa.Float(), nullable=True),
        sa.Column("l1_gas_price_gwei", sa.Float(), nullable=True),
        sa.Column("gas_savings_percent", sa.Float(), nullable=True),
        sa.Column("transaction_count", sa.Integer(), nullable=True),
        sa.Column("block_time", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_l2_metrics_network_timestamp",
        "l2_network_metrics",
        ["network", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_l2_network_metrics_network"), "l2_network_metrics", ["network"], unique=False
    )
    op.create_index(
        op.f("ix_l2_network_metrics_timestamp"), "l2_network_metrics", ["timestamp"], unique=False
    )
    op.create_table(
        "l2_transaction_costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("network", sa.String(length=50), nullable=False),
        sa.Column("eth_transfer_cost_usd", sa.Float(), nullable=True),
        sa.Column("erc20_transfer_cost_usd", sa.Float(), nullable=True),
        sa.Column("uniswap_swap_cost_usd", sa.Float(), nullable=True),
        sa.Column("nft_mint_cost_usd", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_l2_transaction_costs_network"), "l2_transaction_costs", ["network"], unique=False
    )
    op.create_index(
        op.f("ix_l2_transaction_costs_timestamp"),
        "l2_transaction_costs",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "l2_tvl_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("network", sa.String(length=50), nullable=False),
        sa.Column("tvl_usd", sa.Float(), nullable=True),
        sa.Column("tvl_eth", sa.Float(), nullable=True),
        sa.Column("daily_tps", sa.Float(), nullable=True),
        sa.Column("market_share_percent", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_l2_tvl_metrics_network"), "l2_tvl_metrics", ["network"], unique=False)
    op.create_index(
        op.f("ix_l2_tvl_metrics_timestamp"), "l2_tvl_metrics", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_l2_tvl_metrics_timestamp"), table_name="l2_tvl_metrics")
    op.drop_index(op.f("ix_l2_tvl_metrics_network"), table_name="l2_tvl_metrics")
    op.drop_table("l2_tvl_metrics")
    op.drop_index(op.f("ix_l2_transaction_costs_timestamp"), table_name="l2_transaction_costs")
    op.drop_index(op.f("ix_l2_transaction_costs_network"), table_name="l2_transaction_costs")
    op.drop_table("l2_transaction_costs")
    op.drop_index(op.f("ix_l2_network_metrics_timestamp"), table_name="l2_network_metrics")
    op.drop_index(op.f("ix_l2_network_metrics_network"), table_name="l2_network_metrics")
    op.drop_index("idx_l2_metrics_network_timestamp", table_name="l2_network_metrics")
    op.drop_table("l2_network_metrics")
    # ### end Alembic commands ###
