"""Add mev_gas_price_gwei to MEVMetric

Revision ID: f9a8d741038f
Revises: 63d4ee1bb89b
Create Date: 2025-07-10 18:38:36.312545

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9a8d741038f"
down_revision: Union[str, Sequence[str], None] = "63d4ee1bb89b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mev_metrics", sa.Column("mev_gas_price_gwei", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mev_metrics", "mev_gas_price_gwei")
    # ### end Alembic commands ###
